if (plotAngularMode):
    kappas       = numpy.linspace(10, 0, num = 1000, endpoint = False)[::-1]
    angularModes = numpy.degrees(numpy.arcsin(numpy.clip(1 / numpy.sqrt(2 * kappas), a_min = None, a_max = 1)))
    angles       = numpy.linspace(0, 90, num = 900 + 1, endpoint = True)

    pyplot.figure(figsize = (6, 3))
    pyplot.plot(kappas, angularModes, c = "mediumseagreen")
    pyplot.axvline(x = .5, ls = "--", c = "mediumseagreen")
    pyplot.plot([2 / 3., 2 / 3.], [-1., 60.], c = "cornflowerblue", alpha = .5)
    pyplot.plot([1., 1.], [-1., 45.], c = "goldenrod", alpha = .5)
    pyplot.plot([2., 2.], [-1., 30.], c = "tomato", alpha = .5)
    pyplot.plot([0., 2 / 3.], [60., 60.], c = "cornflowerblue", alpha = .5)
    pyplot.plot([0., 1.], [45., 45.], c = "goldenrod", alpha = .5)
    pyplot.plot([0., 2.], [30., 30.], c = "tomato", alpha = .5)
    pyplot.xlim(0, 9)
    pyplot.ylim(0, 90.5)
    ax = pyplot.gca()
    # Major ticks: 0, 1, 2, ..., 9
    ax.set_xticks(numpy.arange(0, 10, 1))
    # Minor ticks: every 1/6
    ax.set_xticks(numpy.arange(0, 9 + 1e-9, 1/6), minor=True)
    # Optional: make minors visually lighter
    ax.tick_params(axis="x", which="minor")
    ax.tick_params(axis="x", which="major")
    pyplot.yticks([0, 15, 30, 45, 60, 75, 90], ["$0$", "$15$", "$30$", "$45$", "$60$", "$75$", "$90$"])
    pyplot.text(0.6, 85, r"$\kappa = \frac{1}{2}$", ha = "left", va = "center")
    pyplot.xlabel(r"Watson distribution concentration $\kappa\ (1)$")
    pyplot.ylabel(r"angular mode $a_\mathrm{p} = \arcsin{\min{\left(\frac{1}{\sqrt{2\kappa}},1\right)}}\ (\degree)$")
    # Put an inset in the top-right. The parameters 'width' and 'height' are fractions of the parent axes.
    ax_in = inset_axes(ax, width="40%", height="40%", loc="upper right", borderpad=1)
    ax_in.plot(angles, inferrer.PDsWatsonPolarAngle(angles, .5), c = "mediumseagreen", ls = "--")
    ax_in.plot(angles, inferrer.PDsWatsonPolarAngle(angles, 2 / 3.), c = "cornflowerblue", alpha = .5)
    ax_in.plot(angles, inferrer.PDsWatsonPolarAngle(angles, 1.), c = "goldenrod", alpha = .5)
    ax_in.plot(angles, inferrer.PDsWatsonPolarAngle(angles, 2.), c = "tomato", alpha = .5)
    ax_in.set_xlim(0, 90)
    ax_in.set_ylim(0, 1.)
    ax_in.set_xticks(numpy.linspace(0, 90, num = 6 + 1, endpoint = True))
    ax_in.set_xlabel(r"polar angle $a\ (\degree)$", fontsize = 8)
    #ax_in.set_ylabel(r"PDF $f_A\ (\mathrm{deg}^{-1})$", fontsize = 8)
    ax_in.set_ylabel(r"PD $f_A(a)\ (\mathrm{deg}^{-1})$", fontsize = 8)
    pyplot.subplots_adjust(left = .1, bottom = 0.14, right = .98, top = .98)
    pyplot.savefig(plotDirectory + "angularModeKappa.pdf")
    pyplot.close()

if (plotMLEExpressionKappa):
    kappas              = numpy.linspace(-9, 9, num = 1800 + 1, endpoint = True)
    MLEExpressionsKappa = inferrer.MLEExpressionKappa(kappas)

    pyplot.figure(figsize = (6, 3))
    pyplot.plot(kappas, MLEExpressionsKappa, c="mediumseagreen")
    #pyplot.plot(kappas, 1 / 3. + 4 / 45. * kappas, c = "mediumseagreen", alpha = .3)#+ 8 / 945. * numpy.square(kappas)
    pyplot.xlim(-9, 9)
    pyplot.xticks(numpy.linspace(-9, 9, num = 7, endpoint = True), ["$-9$", "$-6$", "$-3$", "$0$", "$3$", "$6$", "$9$"])
    pyplot.ylim(-0.02, 1.02)
    pyplot.text(8.8, 1 - .05, r"$\kappa \to \infty{:}\ 1$", ha = "right", va = "center")
    pyplot.text(8.8, .05, r"$\kappa \to -\infty{:}\ 0$", ha = "right", va = "center")
    pyplot.text(8.8, 1 / 3. + .05, r"$\kappa = 0{:}\ \frac{1}{3}$", ha = "right", va = "center")
    #pyplot.text(1, 1 / 3. + .05, r"$\kappa = 0{:}\ \frac{1}{3}$", ha = "left", va = "center")
    pyplot.axhline(0, c = "mediumseagreen", linestyle = ":")
    pyplot.axhline(1 / 3., c = "mediumseagreen", linestyle = ":")
    pyplot.axhline(1, c = "mediumseagreen", linestyle = ":")
    pyplot.xlabel(r"Watson distribution concentration $\kappa\ (1)$")
    pyplot.ylabel(r"$\frac{\exp{\kappa}}{\sqrt{\pi \kappa}\mathrm{erfi}\sqrt{\kappa}}-\frac{1}{2\kappa}\ (1)$")
    pyplot.subplots_adjust(left = .1, bottom = 0.14, right = .98, top = .98)
    pyplot.savefig(plotDirectory + "MLEKappa.pdf")
    pyplot.close()