pyplot.figure(figsize = (6, 3))
pyplot.scatter(kappaJs, logLikelihoods * 1e2, lw = 0, c = "mediumseagreen", alpha = .3)
pyplot.plot(plotKappas, plotLLsLinExp * 1e2, c = "mediumseagreen")
pyplot.plot([kappaMLELinExp, kappaMLELinExp], [0, (a + b * (kappaMLELinExp - w)) * 1e2], c = "black", alpha = .2, ls = "-.")
pyplot.scatter([kappaMLELinExp],[(a + b * (kappaMLELinExp - w)) * 1e2], c = "mediumseagreen", marker = "*", zorder = 5)
pyplot.text(-9.8, .05, r"$\mathcal{L}_\mathrm{fit}(\kappa_\mathrm{j}) = a_1 + a_2\kappa_\mathrm{j} -a_3\exp{\frac{\kappa_\mathrm{j}-a_4}{a_5}}$", ha = "left", c = "gray")
pyplot.xlim(-10, 0)
pyplot.ylim(0, 1.2)
pyplot.xlabel(r"Watson distribution concentration $\kappa_\mathrm{j}\ (1)$")
pyplot.ylabel(r"average log-likelihood $\tilde{\mathcal{L}}\ (10^{-2})$")
pyplot.subplots_adjust(left = .1, bottom = 0.15, right = .98, top = .98)
pyplot.savefig(plotDirectory + "logLikelihood.pdf")
pyplot.close()

pyplot.plot(kappaJs, np.exp(242 * logLikelihoods))
pyplot.show()